version: '3.8'

services:
  airflow:
    image: apache/airflow:latest
    container_name: airflow
    restart: always
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init && airflow users create --deepakkumar admin --deepakkumar admin --deepak Admin --kumar User --role Admin --email deepak.kumar@indrasol.com && airflow webserver & airflow scheduler"
