drop trigger if exists "update_pursuits_updated_at" on "public"."pursuits";

revoke delete on table "public"."pursuits" from "anon";

revoke insert on table "public"."pursuits" from "anon";

revoke references on table "public"."pursuits" from "anon";

revoke select on table "public"."pursuits" from "anon";

revoke trigger on table "public"."pursuits" from "anon";

revoke truncate on table "public"."pursuits" from "anon";

revoke update on table "public"."pursuits" from "anon";

revoke delete on table "public"."pursuits" from "authenticated";

revoke insert on table "public"."pursuits" from "authenticated";

revoke references on table "public"."pursuits" from "authenticated";

revoke select on table "public"."pursuits" from "authenticated";

revoke trigger on table "public"."pursuits" from "authenticated";

revoke truncate on table "public"."pursuits" from "authenticated";

revoke update on table "public"."pursuits" from "authenticated";

revoke delete on table "public"."pursuits" from "service_role";

revoke insert on table "public"."pursuits" from "service_role";

revoke references on table "public"."pursuits" from "service_role";

revoke select on table "public"."pursuits" from "service_role";

revoke trigger on table "public"."pursuits" from "service_role";

revoke truncate on table "public"."pursuits" from "service_role";

revoke update on table "public"."pursuits" from "service_role";

alter table "public"."pursuits" drop constraint "pursuits_user_id_fkey";

alter table "public"."pursuit_assignees" drop constraint "pursuit_assignees_pursuit_id_fkey";

alter table "public"."pursuit_followup_notes" drop constraint "pursuit_followup_notes_pursuit_id_fkey";

alter table "public"."rfp_responses" drop constraint "rfp_responses_pursuit_id_fkey";

alter table "public"."pursuits" drop constraint "pursuits_pkey";

drop index if exists "public"."pursuits_pkey";

drop table "public"."pursuits";

create table "public"."trackers" (
    "id" text not null,
    "title" text not null,
    "description" text,
    "stage" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "due_date" timestamp with time zone,
    "user_id" uuid not null,
    "is_submitted" boolean default false,
    "naicscode" text
);


create table "public"."user_addons" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "addon_type" text,
    "status" text,
    "start_date" timestamp with time zone,
    "stripe_subscription_id" text,
    "updated_at" timestamp with time zone
);


alter table "public"."user_addons" enable row level security;

alter table "public"."user_subscriptions" alter column "stripe_subscription_id" set data type text using "stripe_subscription_id"::text;

CREATE UNIQUE INDEX user_addons_pkey ON public.user_addons USING btree (id);

CREATE UNIQUE INDEX pursuits_pkey ON public.trackers USING btree (id);

alter table "public"."trackers" add constraint "pursuits_pkey" PRIMARY KEY using index "pursuits_pkey";

alter table "public"."user_addons" add constraint "user_addons_pkey" PRIMARY KEY using index "user_addons_pkey";

alter table "public"."trackers" add constraint "pursuits_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) not valid;

alter table "public"."trackers" validate constraint "pursuits_user_id_fkey";

alter table "public"."user_addons" add constraint "user_addons_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_addons" validate constraint "user_addons_user_id_fkey";

alter table "public"."pursuit_assignees" add constraint "pursuit_assignees_pursuit_id_fkey" FOREIGN KEY (pursuit_id) REFERENCES trackers(id) not valid;

alter table "public"."pursuit_assignees" validate constraint "pursuit_assignees_pursuit_id_fkey";

alter table "public"."pursuit_followup_notes" add constraint "pursuit_followup_notes_pursuit_id_fkey" FOREIGN KEY (pursuit_id) REFERENCES trackers(id) ON DELETE CASCADE not valid;

alter table "public"."pursuit_followup_notes" validate constraint "pursuit_followup_notes_pursuit_id_fkey";

alter table "public"."rfp_responses" add constraint "rfp_responses_pursuit_id_fkey" FOREIGN KEY (pursuit_id) REFERENCES trackers(id) not valid;

alter table "public"."rfp_responses" validate constraint "rfp_responses_pursuit_id_fkey";

grant delete on table "public"."trackers" to "anon";

grant insert on table "public"."trackers" to "anon";

grant references on table "public"."trackers" to "anon";

grant select on table "public"."trackers" to "anon";

grant trigger on table "public"."trackers" to "anon";

grant truncate on table "public"."trackers" to "anon";

grant update on table "public"."trackers" to "anon";

grant delete on table "public"."trackers" to "authenticated";

grant insert on table "public"."trackers" to "authenticated";

grant references on table "public"."trackers" to "authenticated";

grant select on table "public"."trackers" to "authenticated";

grant trigger on table "public"."trackers" to "authenticated";

grant truncate on table "public"."trackers" to "authenticated";

grant update on table "public"."trackers" to "authenticated";

grant delete on table "public"."trackers" to "service_role";

grant insert on table "public"."trackers" to "service_role";

grant references on table "public"."trackers" to "service_role";

grant select on table "public"."trackers" to "service_role";

grant trigger on table "public"."trackers" to "service_role";

grant truncate on table "public"."trackers" to "service_role";

grant update on table "public"."trackers" to "service_role";

grant delete on table "public"."user_addons" to "anon";

grant insert on table "public"."user_addons" to "anon";

grant references on table "public"."user_addons" to "anon";

grant select on table "public"."user_addons" to "anon";

grant trigger on table "public"."user_addons" to "anon";

grant truncate on table "public"."user_addons" to "anon";

grant update on table "public"."user_addons" to "anon";

grant delete on table "public"."user_addons" to "authenticated";

grant insert on table "public"."user_addons" to "authenticated";

grant references on table "public"."user_addons" to "authenticated";

grant select on table "public"."user_addons" to "authenticated";

grant trigger on table "public"."user_addons" to "authenticated";

grant truncate on table "public"."user_addons" to "authenticated";

grant update on table "public"."user_addons" to "authenticated";

grant delete on table "public"."user_addons" to "service_role";

grant insert on table "public"."user_addons" to "service_role";

grant references on table "public"."user_addons" to "service_role";

grant select on table "public"."user_addons" to "service_role";

grant trigger on table "public"."user_addons" to "service_role";

grant truncate on table "public"."user_addons" to "service_role";

grant update on table "public"."user_addons" to "service_role";

CREATE TRIGGER update_pursuits_updated_at BEFORE UPDATE ON public.trackers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


