name: SAM CSV Extract and Import

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  extract-and-import:
    runs-on: ubuntu-latest

    env:
      CSV_PATH: ${{ github.workspace }}/ContractOpportunitiesFullCSV.csv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Download latest SAM.gov CSV
        working-directory: ./backend
        env:
          CSV_PATH: ${{ env.CSV_PATH }}
        run: |
          python data_extraction.py

      - name: Import CSV into database (Supabase)
        working-directory: ./backend
        env:
          CSV_PATH: ${{ env.CSV_PATH }}
          SUPABASE_URL_BIZ: ${{ secrets.SUPABASE_URL_BIZ }}
          SUPABASE_SERVICE_KEY_BIZ: ${{ secrets.SUPABASE_SERVICE_KEY_BIZ }}
          SUPABASE_ANON_KEY_BIZ: ${{ secrets.SUPABASE_ANON_KEY_BIZ }}
          OPENAIAPIKEYBIZ: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m app.services.cron.csv_import_sam_gov --csv-path "${CSV_PATH}"


